version: "3.8"

services:
  py1:
    build:
      context: ./docker
      dockerfile: dockerfile_fastapi
    environment:
      - "TZ=Turkey"
    ports:
      - "8001:8001"
    volumes:
      - "./beckend:/app:consistent"
      - "./frontend/static:/static:r"

  npm1:
    build:
      context: ./docker
      dockerfile: dockerfile_npm
    environment:
      - "script=dev"
      - "TZ=Turkey"
      - "NODE_OPTIONS=--openssl-legacy-provider"
    volumes:
      - "./frontend:/app"

  mongodb:
    image: mongo:5.0.3
    environment:
      TZ: "Asia/Istanbul"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - ./docker/mongotool.sh:/archives/mongotool.sh
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pymongodbvol:/data/db
  
volumes:
  pymongodbvol:

