FROM python:3.11.0a3-alpine3.15 AS build
ARG POTR=8001
ENV TZ=Turkey
RUN apk add openssl
COPY ./backend /backend
COPY ./static /static
WORKDIR /backend
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r piplist.txt

EXPOSE $PORT

FROM build AS development
COPY ./env-development.env /etc/app.env
ENTRYPOINT python run.py development $PORT

FROM build AS staging
COPY ./env-staging.env /etc/app.env
ENTRYPOINT python run.py staging $PORT

FROM build AS production
COPY ./env-production.env /etc/app.env
ENTRYPOINT python run.py production $PORT
