FROM python:3.11.0a3-alpine3.15 AS build
ENV TZ=Turkey
RUN apk add openssl
COPY ./backend /backend
COPY ./static /static
WORKDIR /backend
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r piplist.txt
EXPOSE 8001

FROM build AS production
COPY ./production.env /backend/.env
ENTRYPOINT uvicorn --port=8001 --host=0.0.0.0 main:APP

FROM build AS development
ENTRYPOINT uvicorn --reload --port=8001 --host=0.0.0.0 main:APP
