version: "3.8"

services:
  app:
    build:
      context: .
      target: development
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - "./backend:/app/backend:consistent"
      - "./static:/app/static:consistent"
      - "./frontend/src:/app/frontend/src:ro"
      - "./frontend/vite.config.js:/app/frontend/vite.config.js:ro"
      - "node_modules:/app/frontend/node_modules:rw"

volumes:
  mongodata:
  node_modules:
  

