FROM node:17.8-alpine3.14 AS build
ENV TZ=Turkey
ENV NODE_OPTIONS=--openssl-legacy-provider

COPY ./frontend /frontend
WORKDIR /frontend
RUN npm install

FROM build AS development
ENTRYPOINT npm run development
#ENTRYPOINT top

FROM build AS staging
ENTRYPOINT npm run staging

FROM build AS production
ENTRYPOINT npm run production

FROM build AS sandbox
ENTRYPOINT top
