version: "3.8"

services:
  py1:
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      - "TZ=Turkey"
    ports:
      - "8001:8001"
    volumes:
      - "./app:/app"

  mongodb:
    image: mongo:5.0.3
    environment:
      TZ: "Asia/Istanbul"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - ./mongotool.sh:/archives/mongotool.sh
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pymongodbvol:/data/db
  redis:
    image: redis:6.0.8
    environment:
      TZ: "Asia/Istanbul"
    volumes:
      - "pyredisvol:/data:rw"
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
  pymongodbvol:
  pyredisvol:
