version: "3.8"

services:
  py1:
    build:
      context: .
      dockerfile: dockerfile_fastapi
      target: development
    restart: on-failure
    ports:
      - "8001:8001"
    volumes:
      - "./backend:/backend:consistent"
      - "./static:/static:consistent"

  npm1:
    build:
      dockerfile: dockerfile_npm
      target: development
    restart: on-failure
    volumes:
      - "./frontend/src:/frontend/src:ro"
      - "./frontend/vue.config.js:/frontend/vue.config.js:ro"
      - "npm_node_modules:/frontend/node_modules:rw"
      - "./static:/static:rw"

  mongodb:
    image: mongo:5.0.3
    environment:
      TZ: "Asia/Istanbul"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - ./shell/mongotool.sh:/archives/mongotool.sh
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pymongodbvol:/data/db
  
volumes:
  pymongodbvol:
  npm_node_modules:

