FROM node:17.8-alpine3.14
#COPY ./sh_bekle.sh /bekle.sh
RUN npm install -g @vue/cli

WORKDIR /app
COPY ./sh_npm.sh /app/npm.sh
COPY ./package.json /app/package.json
#COPY ./vue.config.js /app/vue.config.js

RUN npm install

CMD ["sh", "/app/npm.sh" ]
