FROM python:3.11.0a3-alpine3.15

RUN apk add openssl
RUN pip install --upgrade pip
WORKDIR /app
COPY piplist.txt ./
RUN pip install --no-cache-dir -r piplist.txt

##COPY ./uvicorn_log.yml /etc/uvicorn_log.yml
COPY uvicorn.sh /uvicorn.sh
CMD ["sh","/uvicorn.sh"]
#CMD ["top"]
