name: Docker Image CI

on: workflow_dispatch

jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image and Push
        env:
          DHTOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          EFILE: ${{ secrets.TEST_ENV_FILE }}
        run: |
          touch ./config/hidden/testdrive.env
          echo $EFILE >> ./config/hidden/testdrive.env
          sh hub.sh haan78 $DHTOKEN baris
