name: Docker Image CI

on: workflow_dispatch

jobs:     

  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Create ENV file       
      env: 
        EFDATA: ${{ secrets.ENV_FILE_STAGING }}
      run: |
        touch ./config/hidden/testdrive.env
        echo $EFDATA > ./config/hidden/testdrive.env
        cat ./config/hidden/testdrive.env
        
    - uses: actions/upload-artifact@v3
    - name: Upload file
      with:
        path: ./config/hidden/testdrive.env

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sh hub.sh haan78 ${{ secrets.DOCKER_HUB_AT }} baris
