name: Docker Image CI

on: workflow_dispatch

jobs:     

  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Create ENV file       
        uses: actions/checkout@v3        
        run: |
          touch ./config/hidden/testdrive.env
          echo ${{ secrets.ENV_FILE_STAGING }} > ./config/hidden/testdrive.env          
          run: sh hub.sh haan78 ${{ secrets.DOCKER_HUB_AT }} baris
