name: Docker Image CI

on: workflow_dispatch

jobs:     

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Override ENV file
      run: echo ${{ ENV_FILE_STAGING }} > ./confi/hidden/staging.env
    - name: Build the Docker image
      run: sh hub.sh haan78 ${{ secrets.DOCKER_HUB_AT }} baris
